socialLinks:
  - platform: github
    url: https://github.com/kadkins4
    showInFooter: true
  - platform: linkedin
    url: https://www.linkedin.com/in/adkinskendall/
    showInFooter: true
  - platform: instagram
    url: https://www.instagram.com/kadkins4/
    showInFooter: true
